# Generated by Django 4.2.11 on 2024-09-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_remove_product_buy_count_product_add_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_weight',
            field=models.FloatField(null=True),
        ),
    ]
