# Generated by Django 4.2.11 on 2024-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_product_add_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
