# Generated by Django 4.2.11 on 2024-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_alter_product_add_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rest_weight',
            field=models.FloatField(default=0),
        ),
    ]
